### ISSUE TITLE
Why have characters.csv?

### ISSUE THREAD

**Issue by xrotwang** [phlorest/bouckaert_et_al2018#1]
In this phylogeny, data and characters are read from an XML file. But why not include characters into data.nex - rather than having data.nex and characters.csv and letting phlorest check for consistency?

In `birchall_et_al2016`, we have characters in `data.nex`. So I'd say - for consistency - we should either extract them for birchall, or merge them into data.nex here.

**Comment by xrotwang** [comment]
@SimonGreenhill ping - github notifications seemed to not work for some time?

**Comment by SimonGreenhill** [comment]
two reasons - 1. the nexus forma is quite restrictive on what it can take in character labels, and 2. I'd intended to add metadata to characters.csv (e.g. concepticon concepts etc)

**Comment by xrotwang** [comment]
So, extracting characters in the birchall_et-al2016 case, too, would be useful, right?

**Comment by xrotwang** [comment]
This would then only be one step away from turning Nexus/BEAST data into a CLDF StructureDataset, with ParameterTable - or just with Paramater_ID = site1 ... siteN. Overkill?

**Comment by xrotwang** [comment]
Ok, for your Austronesian tree that would result in a ~300MB `values.csv` with ~16,000,000 rows. That doesn't seem very useful.
We could still add characters as CLDF ParameterTable, and **also** insert a Characters block into the Nexus data file (possibly with character labels just duplicating the character ID). Then it would at least be possible to read the actual data via NexusReader.data.matrix, and associate it with metadata via ParameterTable.

**Comment by xrotwang** [comment]
So here's my proposal: Similar to "concepts.tsv" in lexibank, we may have `etc/characters.csv` in Phlorest. This file can be edited to add metadata, and will be read and merged with automatically extracted character data into a ParameterTable when running `makecldf`.

**Comment by xrotwang** [comment]
This is what it would look like:
- (partial) additional metadata: https://github.com/D-PLACE/dplace-tree-birchall_et_al2016/blob/main/etc/characters.csv
- merged with extracted characters into ParameterTable: https://github.com/D-PLACE/dplace-tree-birchall_et_al2016/blob/main/cldf/parameters.csv

**Comment by SimonGreenhill** [comment]
Cool -- I've actually done this concepticon reference mapping for a few datasets (and have a few in progress). Let me make these into PR's when i get some time (maybe tomorrow).
